name: Commit Validation

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the validation on

  pull_request:

jobs:
  commit_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to checkout all branches for this Action to work

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.0.1
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt

      # Print the diff in JSON format
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: cat $DIFF

      # Print the diff in raw git format
      - name: print raw diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        run: cat $DIFF      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"

      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas
          pip install gitpython

      - name: Print Diffs
        run: |
          python - << EOF
          import os
          from git import Repo

          repo_path = os.environ['GITHUB_WORKSPACE']
          repo = Repo(repo_path)

          # Get the diff for each commit in the main branch
          for commit in repo.iter_commits('main'):
              print(f"Commit: {commit.hexsha}")
              diff = commit.diff()
              for d in diff:
                  print(f"File: {d.a_path}")
                  print(d.diff.decode('utf-8'))

          # Get the diff for each pull request
          if 'GITHUB_EVENT_PATH' in os.environ:
              import json
              event_path = os.environ['GITHUB_EVENT_PATH']
              with open(event_path) as f:
                  event = json.load(f)
              if 'pull_request' in event:
                  pr_number = event['pull_request']['number']
                  pr = repo.pull_request(pr_number)
                  print(f"Pull Request: {pr_number}")
                  diff = pr.diff()
                  for d in diff:
                      print(f"File: {d.a_path}")
                      print(d.diff.decode('utf-8'))

          EOF

      - name: Run Commit Validation
        run: |
          python validate_commit.py

      - name: Print Pull Request Diff
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: python print_diff.py

      - name: Create Diff Files
        run: |
          for file in ${{ steps.abc.output.modified }}; do
            echo $file
          done

