name: Commit Validation

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the validation on

jobs:
  commit_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Create a requirements.txt file with the necessary dependencies

      - name: Get Previous Commit SHA
        id: prev_commit
        run: |
          echo "::set-output name=sha::$(git log --format=format:%H --skip=1 -n 1)"

      - name: Get Changed Files
        id: changes
        run: |
          git diff --name-only ${{ steps.prev_commit.outputs.sha }} > changed_files.txt

      - name: Create Diff Files
        run: |
          for file in $(cat changed_files.txt); do
            git diff --unified=0 ${{ steps.prev_commit.outputs.sha }} $file > "$file.diff"
          done

      - name: Run Commit Validation
        run: |
          python validate_commit.py $(cat changed_files.txt)  # Change this to the filename of your Python script
