name: Commit Validation

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the validation on

  pull_request:

jobs:
  commit_validation:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Pull Request Diff
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      run: python print_diff.py

      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Create a requirements.txt file with the necessary dependencies

      - name: Create Diff Files
        run: |
          for file in ${{ steps.abc.output.modified }}; do
            echo $file
          done

      - name: Run Commit Validation
        run: |
          python validate_commit.py
